project:
  type: website
  resources:
    - assets/

website:
  title: "Data Portfolio"
  site-url: "https://ralvac178.github.io/data-portfolio/"

  navbar:
    logo: assets/robot.png
    background: primary

    left:
      - text: "Inicio"
        href: index.qmd

    right:
      - icon: github
        href: https://github.com/ralvac178

      - icon: linkedin
        href: https://www.linkedin.com/in/roy-alva/

      - icon: download
        href: assets/Roy_Alva_CV_Data.pdf
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      text: |
        <link rel="icon" type="image/png" href="assets/robot.png">